version: '2.1'
services:
  crmoda-mysql:
    container_name: crmoda-mysql
    image: 'mysql/mysql-server:5.7'
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: crmoda
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3307:3306'
    restart: always
  crm-oda:
    image: crm-oda
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://crmoda-mysql:3306/crmoda?autoReconnect=true&useSSL=false
    volumes:
      - /data/crm-oda
    depends_on:
      crmoda-mysql:
        condition: service_healthy